In [2]:
import numpy as np

ModuleNotFoundError: No module named 'matplotlib'

In [3]:
map_1 = np.load("map1.npy")
plt.imshow(map_1)
plt.show()


In [52]:
start = np.array([0.572538, 0.0608454])
end = np.array([0.300378, 0.406575])

In [53]:
unit_vec = (end-start)/np.linalg.norm(end-start)
dist = np.linalg.norm(end-start)

In [54]:
points = np.array([start+unit_vec*i*0.01 for i in range(int(dist/0.01))])

In [55]:
points[:,0]*=map_1.shape[0]
points[:,1]*=map_1.shape[1]
points = points.astype(int)

array([[200,  40],
       [198,  46],
       [196,  51],
       [193,  56],
       [191,  61],
       [189,  67],
       [187,  72],
       [185,  77],
       [183,  82],
       [180,  88],
       [178,  93],
       [176,  98],
       [174, 103],
       [172, 109],
       [170, 114],
       [167, 119],
       [165, 124],
       [163, 130],
       [161, 135],
       [159, 140],
       [157, 146],
       [154, 151],
       [152, 156],
       [150, 161],
       [148, 167],
       [146, 172],
       [144, 177],
       [141, 182],
       [139, 188],
       [137, 193],
       [135, 198],
       [133, 203],
       [131, 209],
       [128, 214],
       [126, 219],
       [124, 225],
       [122, 230],
       [120, 235],
       [118, 240],
       [115, 246],
       [113, 251],
       [111, 256],
       [109, 261],
       [107, 267]])

In [56]:
for pt in points:
    print(map_1[int(pt[0])-5:int(pt[0])+5,int(pt[1])-5:int(pt[1])+5])

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 1]]
[[0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 1 1 1 1 0 0]
 [0 0 0 0 1 1 1 1 1 0]]
[[1 1 1 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [1 1 1 0 0 0 0 0 0 0]
 [1 1 1

In [57]:
pt = points[2]
map_1[int(pt[0])-5:int(pt[0])+5,int(pt[1])-5:int(pt[1])+5]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=uint8)

In [64]:
int(pt[0])+5

201

In [63]:
int(pt[1])+5

56

In [66]:
map_1[293][66]

1